<!DOCTYPE html>
<html lang="pt-br">
<head>
  <meta charset="UTF-8">
  <!--Let browser know website is optimized for mobile-->
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <!--Import Google Icon Font-->
    <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <!--Import materialize.css-->
    <!-- <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.98.2/css/materialize.css"> -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat|Raleway" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

  <!-- <link rel="stylesheet" type="text/css" href="_assets/_css/materialize.css"> -->
  <link rel="stylesheet" type="text/css" href="_assets/_css/style.css">
  <title>AMG</title>
</head>
<body class="amg-body">
  <section class="v-section land-container">
    <div class="fullscreen-video-wrap">
        <video src="_assets/_img/home-video.mp4" autoplay="true" loop="true">
        </video>
    </div>
    <div class="section-overlay"></div>
    <div class="section-content text-md-center">
      <h2>Amigo Estou Aqui</h2>
      <p>Lorem ipsum, dolor sit amet consectetur adipisicing elit. Id temporibus perferendis necessitatibus numquam amet impedit explicabo? Debitis quasi ullam aperiam!</p>
      <a href="institucional.php" class="btn">Find Out More</a>
    </div>
  </section>
  <a class="scroll-link" href="#content">
      <svg class="mouse" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 76 130" preserveAspectRatio="xMidYMid meet">
      <g fill="none" fill-rule="evenodd">
        <rect width="70" height="118" x="1.5" y="1.5" stroke="#FFF" stroke-width="3" rx="36"/>
        <circle class="scroll" cx="36.5" cy="31.5" r="4.5" fill="#FFF"/>
      </g>
    </svg>
  </a>
  <!-- <div class="section-nav-site">
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>    
  </div> -->
  <div>
  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>    

  </div>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Quo, optio. Autem odio libero, ab laudantium eius excepturi consequuntur laborum eveniet corporis, temporibus sapiente expedita ducimus omnis minus aliquam harum neque ut tenetur, soluta nemo facilis voluptatum ipsum reiciendis optio deserunt! Obcaecati unde, maiores sunt facilis possimus earum animi itaque explicabo. In voluptas obcaecati repellat ratione neque explicabo sunt amet deserunt laudantium quidem aliquam a rerum culpa praesentium nisi, corporis, sequi aspernatur aliquid veniam perferendis corrupti ducimus. Repellat minus debitis assumenda aut ullam voluptas ad possimus, vitae unde quaerat laborum rerum ea odio fugit velit ipsa soluta! Asperiores mollitia, vel commodi!</p>
    </svg>

    </div>
<?php
    require '_includes/footer.php';
?>
